// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62rcH21URyth0bdpjtXveOslSpdW2PlM',
    appId: '1:915693458354:web:4ea8c2d081742270744aab',
    messagingSenderId: '915693458354',
    projectId: 'chatt-4ffaa',
    authDomain: 'chatt-4ffaa.firebaseapp.com',
    storageBucket: 'chatt-4ffaa.firebasestorage.app',
    measurementId: 'G-N3DMNKSG5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdL6KJThrKvfUh_8bSBSKvVYbOalJXiE',
    appId: '1:915693458354:android:e6137db500979f66744aab',
    messagingSenderId: '915693458354',
    projectId: 'chatt-4ffaa',
    storageBucket: 'chatt-4ffaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0nRVTONZJVOJ8FGkOQKUQv-UqJ4O1BY',
    appId: '1:915693458354:ios:2c63b3dd44daa3ed744aab',
    messagingSenderId: '915693458354',
    projectId: 'chatt-4ffaa',
    storageBucket: 'chatt-4ffaa.firebasestorage.app',
    iosBundleId: 'com.example.chatt',
  );
}
